[Service]
Host = "device-random"
Port = 49988
ConnectRetries = 3
Labels = []
OpenMsg = "device random started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = true
File = "/edgex/logs/device-random.log"

[Writable]
LogLevel = "INFO"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/custom-config"

# Pre-define Devices
[[DeviceList]]
  Name = "Random-Integer-Generator01"
  Profile = "Random-Integer-Generator"
  Description = "Example of Device Random"
  Labels = [ "device-random-example" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = "simple01"
    Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "GenerateRandomValue_Int8"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "GenerateRandomValue_Int16"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "GenerateRandomValue_Int32"