name: "Modbus-Sample-Profile"
manufacturer: "Company"
model: "Device-01"
labels:
- "device-modbus"
description: "Example of device-modbus"

deviceResources:
-  ### Boolean ###
  name: "Modbus_DeviceValue_Boolean_RW"
  description: "Generate device boolean value"
  isHidden: true
  tag: "status"
  attributes:
    { primaryTable: "COILS", startingAddress: 0 }
  properties:
    valueType: "BOOL"
    readWrite: "RW"
    scale: 1
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "Modbus_DeviceValue_Boolean_R"
  description: "Generate device boolean value"
  attributes:
    { primaryTable: "DISCRETES_INPUT", startingAddress: 1 }
  properties:
    valueType: "BOOL"
    readWrite: "R"
    scale: 1
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-
  name: "Modbus_DeviceValue_Boolean_W"
  description: "Generate device boolean value"
  attributes:
    { primaryTable: "COILS", startingAddress: 2 }
  properties:
    valueType: "BOOL"
    readWrite: "W"
    scale: 1
    minimum: "0"
    maximum: "1"
    defaultValue: "0"
-  ### Float32 ###
  name: "Modbus_DeviceValue_Float32_RW"
  description: "Generate device float32 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 3 }
  properties:
    valueType: "FLOAT32"
    readWrite: "RW"
    defaultValue: "device float32 value"
-
  name: "Modbus_DeviceValue_Float32_R"
  description: "Generate device float32 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 5 }
  properties:
    valueType: "FLOAT32"
    readWrite: "R"
    defaultValue: "device float32 value"
-
  name: "Modbus_DeviceValue_Float32_W"
  description: "Generate device float32 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 7 }
  properties:
    valueType: "FLOAT32"
    readWrite: "W"
    defaultValue: "device float32 value"
-  ### Float64 ###
  name: "Modbus_DeviceValue_Float64_RW"
  description: "Generate device float64 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 9 }
  properties:
    valueType: "FLOAT64"
    readWrite: "RW"
    defaultValue: "device float64 value"
-
  name: "Modbus_DeviceValue_Float64_R"
  description: "Generate device float64 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 13 }
  properties:
    valueType: "FLOAT64"
    readWrite: "R"
    defaultValue: "device float64 value"
-
  name: "Modbus_DeviceValue_Float64_W"
  description: "Generate device float64 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 17 }
  properties:
    valueType: "FLOAT64"
    readWrite: "W"
    defaultValue: "device float64 value"
-  ### INT16 ###
  name: "Modbus_DeviceValue_INT16_RW"
  description: "Generate device INT16 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 21 }
  properties:
    valueType: "INT16"
    readWrite: "RW"
    minimum: "-32768"
    maximum: "32767"
    defaultValue: "device INT16 value"
-
  name: "Modbus_DeviceValue_INT16_R"
  description: "Generate device INT16 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 21 }
  properties:
    valueType: "INT16"
    readWrite: "R"
    minimum: "-32768"
    maximum: "32767"
    defaultValue: "device INT16 value"
-
  name: "Modbus_DeviceValue_INT16_W"
  description: "Generate device INT16 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 21 }
  properties:
    valueType: "INT16"
    readWrite: "W"
    minimum: "-32768"
    maximum: "32767"
    defaultValue: "device INT16 value"
-  ### INT32 ###
  name: "Modbus_DeviceValue_INT32_RW"
  description: "Generate device INT32 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 23 }
  properties:
    valueType: "INT32"
    readWrite: "RW"
    minimum: "-2147483648"
    maximum: "2147483647"
    defaultValue: "device INT32 value"
-
  name: "Modbus_DeviceValue_INT32_R"
  description: "Generate device INT32 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 23 }
  properties:
    valueType: "INT32"
    readWrite: "R"
    minimum: "-2147483648"
    maximum: "2147483647"
    defaultValue: "device INT32 value"
-
  name: "Modbus_DeviceValue_INT32_W"
  description: "Generate device INT32 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 23 }
  properties:
    valueType: "INT32"
    readWrite: "W"
    minimum: "-2147483648"
    maximum: "2147483647"
    defaultValue: "device INT32 value"
-  ### INT64 ###
  name: "Modbus_DeviceValue_INT64_RW"
  description: "Generate device INT64 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 27 }
  properties:
    valueType: "INT64"
    readWrite: "RW"
    minimum: "-9223372036854775808"
    maximum: "9223372036854775807"
    defaultValue: "device INT64 value"
-
  name: "Modbus_DeviceValue_INT64_R"
  description: "Generate device INT64 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 31 }
  properties:
    valueType: "INT64"
    readWrite: "R"
    minimum: "-9223372036854775808"
    maximum: "9223372036854775807"
    defaultValue: "device INT64 value"
-
  name: "Modbus_DeviceValue_INT64_W"
  description: "Generate device INT64 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 35 }
  properties:
    valueType: "INT64"
    readWrite: "W"
    minimum: "-9223372036854775808"
    maximum: "9223372036854775807"
    defaultValue: "device INT64 value"
-  ### UINT16 ###
  name: "Modbus_DeviceValue_UINT16_RW"
  description: "Generate device uINT16 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 39 }
  properties:
    valueType: "UINT16"
    readWrite: "RW"
    minimum: "0"
    maximum: "65535"
    defaultValue: "device uINT16 value"
-
  name: "Modbus_DeviceValue_UINT16_R"
  description: "Generate device uINT16 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 41 }
  properties:
    valueType: "UINT16"
    readWrite: "R"
    minimum: "0"
    maximum: "65535"
    defaultValue: "device uINT16 value"
-
  name: "Modbus_DeviceValue_UINT16_W"
  description: "Generate device uINT16 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 43 }
  properties:
    valueType: "UINT16"
    readWrite: "W"
    minimum: "0"
    maximum: "65535"
    defaultValue: "device uINT16 value"
-  ### UINT32 ###
  name: "Modbus_DeviceValue_UINT32_RW"
  description: "Generate device uINT32 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 45 }
  properties:
    valueType: "UINT32"
    readWrite: "RW"
    minimum: "0"
    maximum: "4294967295"
    defaultValue: "device uINT32 value"
-
  name: "Modbus_DeviceValue_UINT32_R"
  description: "Generate device uINT32 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 47 }
  properties:
    valueType: "UINT32"
    readWrite: "R"
    minimum: "0"
    maximum: "4294967295"
    defaultValue: "device uINT32 value"
-
  name: "Modbus_DeviceValue_UINT32_W"
  description: "Generate device uINT32 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 49 }
  properties:
    valueType: "UINT32"
    readWrite: "W"
    minimum: "0"
    maximum: "4294967295"
    defaultValue: "device uINT32 value"
-  ### UINT64 ###
  name: "Modbus_DeviceValue_UINT64_RW"
  description: "Generate device UINT64 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 51 }
  properties:
    valueType: "UINT64"
    readWrite: "RW"
    minimum: "0"
    maximum: "18446744073709551615"
    defaultValue: "device UINT64 value"
-
  name: "Modbus_DeviceValue_UINT64_R"
  description: "Generate device UINT64 value"
  attributes:
    { primaryTable: "INPUT_REGISTERS", startingAddress: 55 }
  properties:
    valueType: "UINT64"
    readWrite: "R"
    minimum: "0"
    maximum: "18446744073709551615"
    defaultValue: "device UINT64 value"
-
  name: "Modbus_DeviceValue_UINT64_W"
  description: "Generate device UINT64 value"
  attributes:
    { primaryTable: "HOLDING_REGISTERS", startingAddress: 59 }
  properties:
    valueType: "UINT64"
    readWrite: "W"
    minimum: "0"
    maximum: "18446744073709551615"
    defaultValue: "device UINT64 value"

deviceCommands:
-  ### Boolean ###
  name: "Modbus_GenerateDeviceValue_Boolean_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Boolean_RW"
- name: "Modbus_GenerateDeviceValue_Boolean_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Boolean_R"
- name: "Modbus_GenerateDeviceValue_Boolean_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Boolean_W"
-  ### Float32 ###
  name: "Modbus_GenerateDeviceValue_Float32_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Float32_RW"
-
  name: "Modbus_GenerateDeviceValue_Float32_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Float32_R"
-
  name: "Modbus_GenerateDeviceValue_Float32_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Float32_W"
-  ### Float64 ###
  name: "Modbus_GenerateDeviceValue_Float64_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Float64_RW"
-
  name: "Modbus_GenerateDeviceValue_Float64_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Float64_R"
-
  name: "Modbus_GenerateDeviceValue_Float64_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_Float64_W"
-  ### INT16 ###
  name: "Modbus_GenerateDeviceValue_INT16_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT16_RW"
-
  name: "Modbus_GenerateDeviceValue_INT16_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT16_R"
-
  name: "Modbus_GenerateDeviceValue_INT16_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT16_W"
-  ### INT32 ###
  name: "Modbus_GenerateDeviceValue_INT32_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT32_RW"
-
  name: "Modbus_GenerateDeviceValue_INT32_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT32_R"
-
  name: "Modbus_GenerateDeviceValue_INT32_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT32_W"
-  ### INT64 ###
  name: "Modbus_GenerateDeviceValue_INT64_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT64_RW"
-
  name: "Modbus_GenerateDeviceValue_INT64_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT64_R"
-
  name: "Modbus_GenerateDeviceValue_INT64_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_INT64_W"
-  ### UINT16 ###
  name: "Modbus_GenerateDeviceValue_UINT16_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT16_RW"
-
  name: "Modbus_GenerateDeviceValue_UINT16_R"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT16_RW"
-
  name: "Modbus_GenerateDeviceValue_UINT16_W"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT16_RW"
-  ### UINT32 ###
  name: "Modbus_GenerateDeviceValue_UINT32_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT32_RW"
-
  name: "Modbus_GenerateDeviceValue_UINT32_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT32_R"
-
  name: "Modbus_GenerateDeviceValue_UINT32_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT32_W"
-  ### UINT64 ###
  name: "Modbus_GenerateDeviceValue_UINT64_RW"
  isHidden: false
  readWrite: "RW"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT64_RW"
-
  name: "Modbus_GenerateDeviceValue_UINT64_R"
  isHidden: false
  readWrite: "R"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT64_R"
-
  name: "Modbus_GenerateDeviceValue_UINT64_W"
  isHidden: false
  readWrite: "W"
  resourceOperations:
    - deviceResource: "Modbus_DeviceValue_UINT64_W"
